#!/bin/php
<?php

require 'getopt.php';

$linecount = 10;

$optarg = "";
$remaining_args = 0;
$optind = 1;
while (($x = posix_getopt($argc, $argv, "n:", $optarg, $optind)) != -1) {
	switch ($x) {
		case 'n':
			if (!(int)$optarg) {
				echo "$argv[0]: invalid number of lines: '$optarg'\n";
				exit(1);
			}
			$linecount = $optarg;
			break;
		default:
			echo "usage: $argv[0] [-n number] [file ...]\n";
			exit(1);
			break;
	}
	$remaining_args++;
}

$pos_args = array_slice($argv, $optind);

$count = 0;

if (empty($pos_args)) {
	while($count < $linecount && ($stdin = fgets(STDIN))) {
		echo "$stdin";
		$count++;
	}
	exit(0);
}

foreach ($pos_args as $filename) {
	if (!is_file($filename)) {
		echo "$argv[0]: No such file or directory\n";
		exit(1);
	}

	if (!is_readable($filename)) {
		echo "$argv[0]: Permission denied\n";
		exit(1);
	}
	
	$file = fopen($filename, "r");
	while (!feof($file) && $count < $linecount) {
		echo fgets($file);
		$count++;
	}
	fclose($file);
	exit(0);
}
